### ISSUE TITLE
Install 'rotations' 1.5 failure on Ubuntu 15.10: could not find function "unit"

### ISSUE THREAD

**Issue by yinkaiming1987** [stanfill/rotationsC#1]
Dear guys,

I tried to install package 'rotations' 1.5 on Ubuntu 15.10, but failed.

Command:
install.packages('rotations')

Problems:
installing to /usr/local/lib/R/site-library/rotations/libs
*\* R
*\* data
*\* inst
*\* preparing package for lazy loading
Error in theme(panel.background = element_blank(), panel.grid.minor = element_blank(),  : 
  could not find function "unit"
Error : unable to load R code in package ‘rotations’
ERROR: lazy loading failed for package ‘rotations’
- removing ‘/usr/local/lib/R/site-library/rotations’

Basic Info:
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] rgl_0.95.1247 Rcpp_0.12.0   ggplot2_1.0.1

What could I do?

Thanks,
Kaiming

**Comment by stanfill** [comment]
Hi Kaiming,
Be sure you have the ggplot2 version 2.0.0 or later.  If you do and still have issues, trying installing the  "gridExtra" package as well.  Please let me know if you still have issues.
Thanks,
Bryan

**Comment by yinkaiming1987** [comment]
Thanks Bryan,

It's solved now. It's ggplot2. I update from version 1 to version 2, and
then package rotations 1.5 can be installed.

Best,
Kaiming
