### ISSUE TITLE
Unused kappa argument when calling `ruars` with `rangle=rhaar`

### ISSUE THREAD

**Issue by BertrandSim** [stanfill/rotationsC#4]
When generating rotations with ruars, the following error occurs:

> ruars(10, rhaar)
> Error in rangle(n, kappa, ...) : unused argument (kappa)

This error only occurs with `rangle=rhaar`; other types of `rangle`s that use the `kappa` argument work fine

Edit: This error also occurs in `duars( R, dangle=dhaar)`.

**Comment by stanfill** [comment]
Will be fixed in version 1.6 (out today-ish).
