### ISSUE TITLE
eskewC function crashing

### ISSUE THREAD

**Issue by astamm** [stanfill/rotationsC#7]
The `eskewC()` function always crashes because the matrix size is not initialised. Fix is here : https://github.com/astamm/rotationsC/blob/5000b775905a949e253ddde83090636f40cd3518/rotations/src/basics.cpp#L10. It might be a bug with a sufficient amount of repercussions so as to submit a 1.6.1 version to CRAN.

**Comment by stanfill** [comment]
Fixed and submitted to CRAN
